import { ACTIVE_NOTE_PROMPT_VERSION } from "../types.js";
import { SPYDR_DOMAIN_PROMPT } from "./domain.js";
import { ACTIVE_NOTE_ROUTING_PROMPT } from "./routing.js";
import { ACTIVE_NOTE_OBJECT_DEFINITIONS_PROMPT } from "./object-definitions.js";
import { ACTIVE_NOTE_PROJECT_COHESION_PROMPT } from "./project-cohesion.js";
import { ACTIVE_NOTE_PLANNING_PROMPT } from "./planning.js";
import { ACTIVE_NOTE_GUARDRAILS_PROMPT } from "./guardrails.js";

export {
  SPYDR_DOMAIN_PROMPT,
  ACTIVE_NOTE_ROUTING_PROMPT,
  ACTIVE_NOTE_OBJECT_DEFINITIONS_PROMPT,
  ACTIVE_NOTE_PROJECT_COHESION_PROMPT,
  ACTIVE_NOTE_PLANNING_PROMPT,
  ACTIVE_NOTE_GUARDRAILS_PROMPT,
};

export const ACTIVE_NOTE_SYSTEM_PROMPT = [
  SPYDR_DOMAIN_PROMPT,
  ACTIVE_NOTE_ROUTING_PROMPT,
  ACTIVE_NOTE_OBJECT_DEFINITIONS_PROMPT,
  ACTIVE_NOTE_PROJECT_COHESION_PROMPT,
  ACTIVE_NOTE_PLANNING_PROMPT,
  ACTIVE_NOTE_GUARDRAILS_PROMPT,
  `Prompt version: ${ACTIVE_NOTE_PROMPT_VERSION}`,
].join("\n\n");
