import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const appDir = path.dirname(fileURLToPath(import.meta.url));
const htmlPath = path.join(appDir, "ui-dist/index.html");
const outPath = path.join(appDir, "list-view-html.generated.ts");

if (!fs.existsSync(htmlPath)) {
  console.error(`Missing ${htmlPath}. Run vite build first.`);
  process.exit(1);
}

const html = fs.readFileSync(htmlPath, "utf8");
const source = `/* Auto-generated by embed-mcp-app.mjs — do not edit. */
export const EMBEDDED_LIST_VIEW_HTML = ${JSON.stringify(html)};
`;

fs.writeFileSync(outPath, source, "utf8");
console.log(`embedded mcp-app html (${html.length} chars) -> list-view-html.generated.ts`);
